# Icon
favicon: /favicon.ico
# SEO
keywords: 读书, 札记, 笔记, 手记, 前端开发
# Header
# https://picsum.photos/1920/800/?random
page_background: /img/
page_menu_button: dark
post_background: /img/
post_menu_button: light
title_plancehold: 札记
author:
  head: https://avatars2.githubusercontent.com/u/5219949?v=4&s=460
  signature: 或学而有得，或思而有得，辄札记之。
navication:
  - name: Github
    link: https://github.com/consolejs
  - name: Hello
    link: /hello.html
# content
content_width: 800
# Footer
## Social icon list: [facebook, twitter, weibo, wechat, github, stackoverflow, linkin, email, segmentfault, flickr, zhihu, disqus, douban, bilibili]
social:
  - name: Github
    icon: github
    link: /
  # - name: Weibo
  #   icon: weibo
  #   link: https://weibo.com/heqibang
  # - name: SegmentFault
  #   icon: segmentfault
  #   link: https://www.segmentfault.com/u/bon

# Comment From 来必力
# https://livere.com/
comments:
  enable: true
  siteName: livere
# Copyright
copyright:
  record: false
  hexo: false
  laughing: false